### PR TITLE
Add Pickup System and Magnet Powerup

### PR DESCRIPTION
**Pull request by aJoph**
And a resource-based base to extend into other powerups. 

**There is something missing:** An indicator that the power up is active. I remember discussion of how it'd be, but not the conclusion so I'll just leave it here for the moment.

### CODE REVIEW

**Comment by Trikzon** [comment]
Thank you for making this! I think that we should consider making your powerup system more generic than just for powerups. You made a `PowerupPickup`, but maybe it should be just a `PickupInstance` that also includes treasure and have treasure be a pickup too. So the `Powerup` resource would be a `Pickup` resource instead, and treasure would be one of the pickups. That way we can change the `TreasureCollector` to a `PickupCollector` and the `TreasureSpawner` to a `PickupSpawner`.

**Comment by aJoph** [comment]
Will do.

**Comment by Trikzon** [comment]
How is this going? I'd like to get this change done in the next couple of days. I can pick it up where you left it if you will be busy

**Comment by aJoph** [comment]
> How is this going? I'd like to get this change done in the next couple of days. I can pick it up where you left it if you will be busy
@Trikzon 
The powerup system is finished I was just having trouble making it work with the Treasure system, and ended up deleting all my work to start fresh, and... Yeah. I was planning on finishing it today but I'll be unable to hop on today's meeting like I planned.
 
I did not leave the latest commit in a presentable state so If you decide it's all unworkable 'cuz overengineering and the likes, then that's fine, no hurt feelings.  Sorry for the trouble.

**Comment by aJoph** [comment]
Actually never mind, it seems when I last left off, I broke functionality...

**Pull request closed without merging**
